### ISSUE TITLE
What are hccl64 and toplnx?

### ISSUE THREAD

**Issue by snhirsch** [749/UltraDefrag4Linux#1]
Interested in building for 64-bit AMD Linux, but I can find nothing on the web relative to either of those tools.  Can you point me to a link?  Thanks!

Ahhh.  Nevermind.  The default Makefile more or less works with this change:
```
diff --git a/src/Makefile b/src/Makefile
index 016f9c3..dfeda3e 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -24,9 +24,15 @@ AR=ar
 INCL=-I/usr/include -Iinclude
 COPT=-DLXGC=1 -O2
 GCCOPT=-DLXGC=1 -O2
-LIB1=/usr/lib64
-LIB2=/usr/lib/gcc/x86_64-pc-linux-gnu/$(GCC_VERSION)
-NTFSLIB=/lib64/libntfs-3g.so.*.0.0
+
+# LIB1=/usr/lib64
+# LIB2=/usr/lib/gcc/x86_64-pc-linux-gnu/$(GCC_VERSION)
+# NTFSLIB=/lib64/libntfs-3g.so.*.0.0
+
+# For Ubuntu 18.04
+LIB1=/usr/lib/x86_64-linux-gnu
+LIB2=/usr/lib/gcc/x86_64-linux-gnu/$(GCC_VERSION)
+NTFSLIB=/lib/x86_64-linux-gnu/libntfs-3g.so.*.0.0
 
 A=console.a udefrag.a zenwinx.a wincalls.a
```

**Comment by 749** [comment]
Sorry for the late reply.

Thank you for your interest and posting your solution. C is not my primary programming language, so my debugging skills are low. I mostly built this repository because I wanted to see what if any Features where added in the Windows version. But I realized, that they just added a UI on Top and that is it.

The only addition of mine is adding colors to the console output: https://github.com/749/UltraDefrag4Linux/commit/6a6b3229879b7a482671292a7ca86faad1c92cd9

Thank you for the fixes to the Makefile I have added them as a Comment: https://github.com/749/UltraDefrag4Linux/commit/12b1bf70e95fdefd4753bffd419ef0089e41760b
